### ISSUE TITLE
Split up media APIs

### ISSUE THREAD

**Issue by marcobiedermann** [toddmotto/public-apis#127]
I suggest splitting the media APIs up into:
* Blogs (e.g. Medium)
* Books (e.g. Good Reads)
* Images (e.g. Unsplash, Flickr, Imgur, dribbble)
* Media (e.g. Chuck Norris Database, Rijksmuseum)
* Music (e.g. Soundcloud, iTunes, TheMovieDB)
* Social (e.g. Facebook, Twitter, G+)
* Video (e.g. YouTube, Vimeo)

**Comment by davemachado** [comment]
This issue should be fixed in PR #231

**Comment by davemachado** [comment]
This issue can be closed. PR #231 has been merged into master.
