### ISSUE TITLE
Why this when http://www.programmableweb.com/ has 14K+ APIs listed?

### ISSUE THREAD

**Issue by GaloisGirl** [toddmotto/public-apis#139]
I'm genuinely asking: isn't this re-inventing the wheel a bit?

**Comment by toddmotto** [comment]
This was put together after a series of tweets I got from others who use specific and their favourite go-to APIs. Rather than a mountain collection it's what the industry use and will help others find the best APIs out there.

**Comment by 2br-2b** [comment]
Might it be good to leave a link to Programmable Web as a backup - "If you can't find your api here, programmableweb.com has over 20,000 to check out and search through!"
