### ISSUE TITLE
Indicate whether HTTPS is supported

### ISSUE THREAD

**Issue by jakearchibald** [toddmotto/public-apis#159]
Since progressive web apps need to be served securely, so do the APIs they use.

**Comment by mikestreety** [comment]
This is the next one we need to tackle. Would just suggest a "https" column with a simple yes/no answer?

**Comment by davemachado** [comment]
I can't think of any reason another simple column wouldn't suit our needs. It will also keep things sane in the event of possible JSON-ification.
