### ISSUE TITLE
Make everything alphabetical

### ISSUE THREAD

**Issue by mikestreety** [toddmotto/public-apis#191]
I think this was done as a PR before all the updates and was decided it would be done after - just raising an issue so we have something to reference/close.

Notes:

I think the transport one needs some consistency. I would say put country, city (and then in alphabetical order) so that all the cities sit together in countries

**Comment by wesbos** [comment]
Would be cool to move all this data over to a javascript object and then we can parse / displayit however we want.

**Comment by montogeek** [comment]
@wesbos Exactly, then build a website like http://styleguides.io/ to filter them :)

**Comment by jbrooksuk** [comment]
I'll order everything once the PR's are done, then we can go through and move everything into JSON objects if we want :)
