### ISSUE TITLE
Change category name

### ISSUE THREAD

**Issue by diegobrum** [toddmotto/public-apis#269]
I think than word _**"Food"**_ represents better the idea of category instead of word _**"Drinks"**_

**Comment by jbrooksuk** [comment]
Food & Drink?

**Comment by diegobrum** [comment]
Can be :)

**Comment by mikestreety** [comment]
Dammit, i got the issue number wrong ;) https://github.com/toddmotto/public-apis/commit/1cd280a8ab42a6993c995895b1ffc7dd061a62ff
