### ISSUE TITLE
A public-apis api

### ISSUE THREAD

**Issue by JoshCheek** [toddmotto/public-apis#285]
<3 the project :) I was thinking it would be nice to filter the list to see only the public apis. Since it's just a markdown file, there is not a way to do this, so I wrote a script to extract it:

```sh
curl -s 'https://raw.githubusercontent.com/toddmotto/public-apis/db03add118d8a2205b2de63d400865fe4c169f62/README.md' | ruby -ne '
   BEGIN { prev = "" }
   table = /^\|/
   delimiter_row = /^[-|]+$/
   if prev !~ table && ~table
     # noop
   elsif ~delimiter_row
     # noop
   elsif ~table
     print
   end
   prev = $_' | ruby -rjson -ne '
   BEGIN { header = %i[api desc auth https link] }
   BEGIN { rows = [] }
   END   { puts JSON.dump rows }
   cells = $_.split("|").map(&:strip).select { |s| !s.empty? }
   row   = header.zip(cells).to_h
   row[:auth]  = row[:auth].match?  /yes/i
   row[:https] = row[:https].match? /yes/i
   row[:link]  = row[:link][6...-1]
   rows << row
   '
```

Then, to answer my question was to pipe that output through [jq](https://stedolan.github.io/jq/):

```sh
... | jq '.[] | select(.auth==false) | .api'
```

IDK if this is useful to anyone else, but figured I'd put it out there, in case anyone else was wanting to do something like this (note that I have a [caching script](https://github.com/JoshCheek/dotfiles/blob/fcd91ed8502f810863780df9055d7143fe58f368/bin/cache) so that I can experiment without hitting the endpoint over and over)

**Comment by JoshCheek** [comment]
Going to close this now, no reason to keep it open, just figured I'd document the thought :)

**Comment by davemachado** [comment]
Thanks for the info @JoshCheek ! There's currently an open issue in discussion (issue #203 ) that would cover filtering as well, if a website does come out of it- FYI.
