### ISSUE TITLE
Link timeouts on CI builds

### ISSUE THREAD

**Issue by davemachado** [toddmotto/public-apis#297]
Since we now have beautiful CI checking link validity on every PR, it seems like there will need to be a conversation regarding when links should be removed. For example, as of 1:00PM EST, there is this "dead" link in the build:

<img width="428" alt="screen shot 2017-03-03 at 1 01 43 pm" src="https://cloud.githubusercontent.com/assets/15134885/23562719/adb80612-0011-11e7-85c7-571948920ba6.png">

As a general statement, should any link be immediately removed when it dies via timeout, even if it was working fine just the other day? Should it be a "let's wait a few days and see if it comes back within X days" situation? 

Comments, questions, concerns, etc,  are welcome!

Note: The contributing guide currently says that contributors should not be concerned with their individual PR's if the links that are failing in the build are unrelated.

**Comment by jbrooksuk** [comment]
Let's wait a few days and fact check before making a decision. We could create an issue or PR discussing as appropriate.
