### ISSUE TITLE
goodreads dont have full JSON api

### ISSUE THREAD

**Issue by anagami** [toddmotto/public-apis#308]
Hi! thanks for good list public api!
i try goodreads and was dissapointed, because they api have just few methods wich can response with JSON format
and looking like they don't have any plans to realise this https://www.goodreads.com/topic/show/453508-can-we-get-json-for-all-calls

**Comment by davemachado** [comment]
Hello there. I'm sorry to hear you were disappointed with goodreads' XML-based API. However, this list is not any form of administration for the listed APIs. Instead, this list is to serve as a central location where developers can quickly find a free API to use for a hobby, side project, automation, etc. As a side note, there are many great tools out there to easily convert XML to JSON that are just a quick Google search away. Best of luck with your project!
