### ISSUE TITLE
There is another similar repo here https://github.com/abhishekbanthia/Public-APIs

### ISSUE THREAD

**Issue by joelbandi** [toddmotto/public-apis#335]
It's not as popular though...do you think it's good to merge these two lists ?

the repo is located here : [https://github.com/abhishekbanthia/Public-APIs](https://github.com/abhishekbanthia/Public-APIs)

**Comment by davemachado** [comment]
Hi @joelbandi , it looks like this other list includes trial-based APIs, as well as some other broader topics. This list contains only free APIs, or APIs with some form of a "free tier," so it doesn't appear that there is much overlap between the two. Always good to know about other resources though :)
