### ISSUE TITLE
Finance APIs

### ISSUE THREAD

**Issue by ratchakr** [toddmotto/public-apis#344]
Hi,

First of all, thanks a ton for presenting the curated list of openAPI-s. This is of great help!
One thing I would like to mention is for the Fiance API-s, the free version of barcartondemand (https://www.barchartondemand.com/free) API-s provides only two API-s, one is the GetQuote and the other one is GetHistory; both of these are limited in their usage. When I inquired further, I found out the api-s like getRatings() and get real time data feed API-s are not free. It would be great if you can list any other Finance API provider that comes free with API-s such as  getQuote, getHistory, getRating etc.

Thanks.

**Comment by davemachado** [comment]
Hi @ratchakr, feel free to open a pull request with any services you'd like to add to this collection!

**Comment by ratchakr** [comment]
Sure @davemachado.
