### ISSUE TITLE
Added labels

### ISSUE THREAD

**Issue by mikestreety** [toddmotto/public-apis#425]
_There is no way to add comments, so I'm making an issue only to close it soon_.

I've added a few labels to the repo so looking at the PRs is easier.

- `Contributor input required` - added if one of the reviewers has asked the original contributor needs to update their PR, whether it is removing files or sorting alphabetically
- `Second opinion required` - If a second reviewer needs to have a look and offer their opinion
- `Functionality improvement` - if this pr improves the build process or similar, rather than adding an API

Hope this is ok! Means we can quickly look at what PRs are and what they are waiting for :)

@davemachado @jbrooksuk

**Comment by davemachado** [comment]
@mikestreety I like the separation of List enhancement vs Infrastructure enhancement - works for me!

**Comment by davemachado** [comment]
Maybe add `new entry` and `update entry` so we can keep record on how many new vs updates over time?

**Comment by mikestreety** [comment]
@davemachado I think that might be over complicating things 😉

**Comment by jbrooksuk** [comment]
Nice separation!

**Comment by davemachado** [comment]
@mikestreety oh well, worth a shot ;)
