### ISSUE TITLE
Open Public Data

### ISSUE THREAD

**Issue by mik-laj** [toddmotto/public-apis#430]
Hi
Many public data in machine readable format is availabie  at: 
https://www.europeandataportal.eu/
Many countries also have local sites that collect data:
http://danepubliczne.gov.pl/ (Poland)
http://data.gov.ru/ (Russian. Yes. They have a very good portal to share information for citizens)
Other at: https://www.europeandataportal.eu/data/en/organization

On this sites, you could found very good public API: 
Poland: https://danepubliczne.gov.pl/dataset?api=with_api 

Thanks in advance

**Comment by davemachado** [comment]
Hi @mik-laj , thanks for sharing these links. If you'd like to incorporate some of these services into this project, feel free to open a pull request!
