### ISSUE TITLE
Consolidate api lists with abhishekbanthia/Public-APIs

### ISSUE THREAD

**Issue by styfle** [toddmotto/public-apis#437]
There is another list of public APIs that has a lot of stars: https://github.com/abhishekbanthia/Public-APIs

Should these two efforts be combined?

Related: https://github.com/abhishekbanthia/Public-APIs/issues/154

**Comment by mikestreety** [comment]
Hey @styfle, thanks!

This has already been suggested - [the answer to the previous issue](https://github.com/toddmotto/public-apis/issues/335) still stands. 😄 

Thanks anyway - look forward to seeing some PRs 👍
