### ISSUE TITLE
Rename Data Access to Open Data?

### ISSUE THREAD

**Issue by bekicot** [toddmotto/public-apis#443]
By analyzing the content of Data Access section, I saw the content of it have a better categorized into Open Data. 

Wikipedia said [Data Access](https://github.com/krispo/awesome-haskell/issues/29)
> Data access typically refers to software and activities related to storing, retrieving, or acting on data housed in a database or other repository.

In my interpretation, it means people typically think of data access as an action of a data, instead of as somethings related into data itself. I also have this difficulty understanding it while making #442 .

In my opinion, it will be better if it renamed into "Open Data". What do you guys think? :)

**Comment by davemachado** [comment]
I think that's fine, I've had that same thought myself a few times. Would be interested in others' thoughts as well.

**Comment by jbrooksuk** [comment]
Yep!
