### ISSUE TITLE
quick update - better builds and site plan

### ISSUE THREAD

**Issue by davemachado** [toddmotto/public-apis#451]
I wanted to post an update as to what I have currently cooking. As with most of this update posts, I will close this in some time if no one has any questions.

I received a response from DigitalOcean back when I reached out to them this past December, when website talks first started brewing. I'm planning to move forward to use one of their VMs to facilitate a more interactive environment. The biggest thing that currently pains me on this project is the CI build status. Right now, the build status is used to indicate whether any links in the project are unavailable. That's great, but the status won't update until a new build is kicked off, or someone restarts the current master build to check the links (something I currently do several times a day to give as close to a current status as possible). Starting small, this simple server can babysit this process, ensuring that the status of the project is an accurate reflection on the status of the resources.

In parallel to this, as everyone is hopefully aware, I'm working on a site plan for this project, currently gearing towards using Vue.js to facilitate generating a table from the JSON.

 Cheers! 🍻

**Comment by jbrooksuk** [comment]
🎉

**Comment by mikestreety** [comment]
:🎊

**Comment by davemachado** [comment]
🎈
