### ISSUE TITLE
current build status is broken

### ISSUE THREAD

**Issue by DanielFGray** [toddmotto/public-apis#453]
currently the json build is an empty object

https://github.com/toddmotto/public-apis/blob/master/json/entries.json

**Comment by davemachado** [comment]
Well that's not good! I've manually created JSON files in commit c16374a3f3ac70d1c70d77315df552830fefb2ee and will look into the build failure now

**Comment by davemachado** [comment]
Alright, everything's back in working order. Drum roll please...

Unfortunately, Travis CI only supports up to v7 of Node.js, which the new condensation script did not appreciate. When that script failed, the JSON generation script had no Markdown tables to convert, so it uploaded an empty object. 

After downgrading the condensation script, everything is chugging along nicely. During debugging, I made some small improvements to the logic that determines if a build has a valid JSON candidate to deploy. That check should prevent situations like this happening again.

Thanks for bringing this up @DanielFGray .
