### ISSUE TITLE
Interest in merging projects?

### ISSUE THREAD

**Issue by karllhughes** [toddmotto/public-apis#481]
I've been doing a lot of searching for lists of APIs like this lately. I just ran across [@abhishekbanthia's similar list of public/free apis](https://github.com/abhishekbanthia/Public-APIs).

I'm curious if there's any reason not to work towards combining the two projects? I'm interested in helping if it makes sense.

I also posted an issue on his project to see if he's got any interest: https://github.com/abhishekbanthia/Public-APIs/issues/165

**Comment by davemachado** [comment]
Hi @karllhughes , thanks for supporting the project!

This has already been suggested - [the answer to the previous issue](https://github.com/toddmotto/public-apis/issues/335) still stands. 😄 

This project also includes extra info (e.g HTTPS and Auth type, and soon to be CORS).

Looking forward to reviewing some awesome PRs from you in the future 👍

**Comment by karllhughes** [comment]
Ok, fair enough. I didn't notice the differences on first blush. I've got a bunch of APIs to add, hoping to have a first stab at a PR for you tomorrow. Thanks for putting this together!
