### ISSUE TITLE
New section proposal: Mock Data

### ISSUE THREAD

**Issue by karllhughes** [toddmotto/public-apis#511]
We now have many lorem ipsum and mock data generators in the `Development` section. What do you think about making a new section for `Mock Data` or `Data Generation`?

Happy to make a PR, just curious if any maintainers have preferences on what the name of the new category should be?

**Comment by davemachado** [comment]
`Mock Data` sounds good to me - I've been planning to go in and work to split out some chunks of the `Development` section, since that is the biggest catch-all currently, but I would like to push out changes for CI and site from my backlog first.

**Comment by karllhughes** [comment]
Ok, @davemachado just let me know if you'd like me to help 😄

**Comment by jbrooksuk** [comment]
Maybe Testing?

**Comment by davemachado** [comment]
Thanks @karllhughes for the offer, I just opened PR #514 to cover this 🎉
