### ISSUE TITLE
Add Coindata.co.za

### ISSUE THREAD

**Issue by ErikThiart** [toddmotto/public-apis#575]
I have no clue how to make a pull request.

Can we add their API to the cryptocurrency section?
Auth none
https://coindata.co.za/api.php

**Comment by davemachado** [comment]
Hi @ErikThiart , I see that you are credited with building the API in question. Is there a documentation page for this service? We do not like linking to a live request URL as it can interfere with our validation process.

**Comment by davemachado** [comment]
@ErikThiart nudge

**Comment by davemachado** [comment]
closing now. feel free to re-open if needed.
