### ISSUE TITLE
Where source data come?

### ISSUE THREAD

**Issue by reilue** [toddmotto/public-apis#588]
Hello there, this repo is a great resource. It's absof*ckinglutely awesome the data given by the API's, but i'm asking to myself, where all this data come? where is the source?. The "Fake News" trend is here, and as glasses for a myope, i want to everybody know who, what, where, is the content we're are comsuming.

So, how do we know such thing for this API's?.

Any suggestion to address a possible solution are more than welcome.

**Comment by reilue** [comment]
@davemachado  Thank for the reply and the explanation. Doing what you propose require an amount of work that would heal the internet for misinformation. But for now, and for the sake of brevity and quickly solution. For every information retrieve, mention ( and just for now ) the source of such data. As a source in a graph when any journal, industry, institution, present it.

**Comment by davemachado** [comment]
I did not understand your comment. Could you please explain again in a different wording?

**Comment by davemachado** [comment]
Closing aged issue.
