### ISSUE TITLE
Add Marvel API in the comics section

### ISSUE THREAD

**Issue by sarang-s** [toddmotto/public-apis#616]
Thanks for looking to open an issue for this project.

If you are opening an issue to suggest adding a new entry, please consider opening a pull request instead!

**Comment by davemachado** [comment]
Hi @sarang-s , do you have any information on this API? I cannot see pricing information without signing in. Thanks.

**Comment by davemachado** [comment]
@sarang-s poke 😄

**Comment by davemachado** [comment]
Closing as this is now two weeks old. @sarang-s if you have more information, please open a Pull Request.
