### ISSUE TITLE
Travis CI build falied on commits

### ISSUE THREAD

**Issue by fayazara** [toddmotto/public-apis#633]
Why do I keep getting <i>The Travis CI build failed</i> when I have updated the file as per contributin guidelines?
Please have a look at [PR#631](https://github.com/toddmotto/public-apis/pull/631) & let me know how I can fix it, so that I can contribute.

**Comment by davemachado** [comment]
Looking at your PR changes I can already see that your additions are not in alphabetical order (which can be confirmed by reading the log that Travis CI provides).
