### ISSUE TITLE
Allow two new options for the Auth field

### ISSUE THREAD

**Issue by abhinavk99** [toddmotto/public-apis#657]
I would like to add the [Livecoin API](https://www.livecoin.net/api?lang=en) but authentication for it requires two HTTP headers. Would you be willing to consider adding `Headers` as an acceptable option for the `Auth` field?

**Comment by abhinavk99** [comment]
Furthermore, the [Official MyAnimeList API](https://myanimelist.net/modules.php?go=api) uses [Basic Access Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication), which isn't an acceptable `Auth` option either.

**Comment by davemachado** [comment]
Hi @abhinavk99 , thanks for bringing this up. Can you please describe what values the two headers hold for Livecoin?

**Comment by davemachado** [comment]
Livecoin could be submitted with `No` as the Auth type, since it says some services require no auth. 

Adding `Basic` as an Auth type is fine, so if you could open a PR that adds some service with a Basic auth type, I will update that same PR to with the required build fixes to pass CI.

Thanks!

**Comment by abhinavk99** [comment]
I added Livecoin in #662. I ended up not adding `Basic` as an Auth type because I just realized that the API service that uses it is an XML API, not JSON.
