### ISSUE TITLE
Link to MailTest API webpage not working

### ISSUE THREAD

**Issue by palashmon** [toddmotto/public-apis#664]
First of all thanks do much for this repo. 

I found a small link related issue today.
Under [Data Validation](https://github.com/toddmotto/public-apis#data-validation) > MailTest API webpage link is not working.

Current link: http://mailtest.in/documentation/
On opening the page it shows a static page with message like:
> This Domain Name Has Expired - Renewal Instructions.

Please review this once.

Regards!

**Comment by davemachado** [comment]
Hi @palashmon , I'm going to give MailTest a day or two more to resolve their domain issue, and if it is still offline I will remove it.

**Comment by davemachado** [comment]
Will be removing this link during an upcoming cleanup commit.

**Comment by davemachado** [comment]
Fixed in 33c5608c857f15eb3cd39e825d0a3fa3e7dd5371
