### ISSUE TITLE
More detailed auth values

### ISSUE THREAD

**Issue by abalone23** [toddmotto/public-apis#747]
I'd like to see more detailed values for the auth column, like OAuth 1.0, OAuth 2.0, cookie, Bearer, Digest Basic etc.

**Comment by davemachado** [comment]
Hi @abalone23 , thanks for raising this issue. The issue with adding more specific values for the auth column is that over time the cardinality of values grows very quickly. If you would like to comb through the current listings and see how widespread that column would become and report back with more concrete data, that would be great! Until then, or until someone else decides to pick up that torch and run with it, I am going to close this issue.

**Comment by abalone23** [comment]
Thank you for the explanation.
