### ISSUE TITLE
Need to allow more fields in Auth type

### ISSUE THREAD

**Issue by s-nirali** [toddmotto/public-apis#802]
The Auth type does not accept values of headers such as `Authorization` header and fails the Travis CI build.

**Comment by s-nirali** [comment]
Yes, it is in connection to PR #801 . The header is `Authorization` and it's value is a signature derived from an [algorithm](https://docs.aws.amazon.com/general/latest/gr/signature-version-4.html) specified on the AWS website.

**Comment by davemachado** [comment]
Since #801 is now closed , I will be closing this issue as well.
