### ISSUE TITLE
Open Api Specification

### ISSUE THREAD

**Issue by lukesmurray** [toddmotto/public-apis#813]
For apis which have a public open api specification, there is additional power given to the developer such as the ability to automatically generate a client, a server, documentation, testing and more. This page has a collection of projects which support the above-mentioned abilities  https://apis.guru/awesome-openapi3/. 

I was wondering if people in the list have any interest in adding a column to this list to link the open api specification if it is available. Alternatively, does anyone know of a list which contains links to open api specifications?

Here is an example of an api specification for The Movie DB. https://api.stoplight.io/v1/versions/9WaNJfGpnnQ76opqe/export/oas.json

**Comment by davemachado** [comment]
Hi @lukesmurray , thanks bringing this up. Allowing every entry to link to its preferred documentation was worked well for us for quite some time. I also would feel pretty confident that most entries in this project do not support this specification, so the extra column would be empty more times than not. I'm going to close this issue for now, but please feel welcome to contribute to the project in the future!

Hope you enjoy this xkcd comic regarding "standards" and "specifications" :)
https://xkcd.com/927/
