### ISSUE TITLE
Auth field value for cryptocurrency micropayments

### ISSUE THREAD

**Issue by torkelrogstad** [toddmotto/public-apis#818]
The available values for the Auth field are not really enough for the API that [SuredBits](https//suredbits.com) (disclaimer: I work with SuredBits) provides. The SuredBits sports API utilizes bitcoin micro payments, were you either pay per API call or pay for a set amount of time with API data being streamed to you. 

A fitting field for such APIs could be pay-per-call/PPC, micropayments, cryptopayments, or something similar.

**Comment by davemachado** [comment]
Hi @torkelrogstad , unfortunately any service that is fee-based cannot find a home in this project.
