### ISSUE TITLE
I build the website with the README history and I'm also adding more metadata to the cards as author, commiter and date.

### ISSUE THREAD

**Issue by mddanishyusuf** [toddmotto/public-apis#846]
I build the website with the README history and I'm also adding more metadata to the cards as author, commiter and date.

https://public-apis.xyz

let me know your thought on this.

Thanks

_Originally posted by @mddanishyusuf in https://github.com/toddmotto/public-apis/issues/203#issuecomment-451571107_

**Comment by jbrooksuk** [comment]
The site is no longer working.
